// ============================================
// MOCK DATA - Capittal CRM Cierre
// ============================================

import type {
  Mandato,
  Cliente,
  EmpresaTarget,
  Tarea,
  Documento,
  Actividad,
} from "@/types";

// ============================================
// MANDATOS
// ============================================
export const mockMandatos: Mandato[] = [
  {
    id: "M-001",
    empresa: "TechCorp Solutions",
    cliente: "María García",
    clienteId: "C-001",
    tipo: "venta",
    estado: "En progreso",
    valor: "€2.5M",
    fecha: "2024-01-15",
    descripcion: "Venta de empresa tecnológica especializada en IA",
    sector: "Tecnología",
    ubicacion: "Madrid",
    responsable: "Juan Díaz",
    documentosCount: 12,
    actividadesCount: 8,
    targetsCount: 3,
    tareasAbiertas: 2,
    ultimaActualizacion: "2024-02-05",
  },
  {
    id: "M-002",
    empresa: "InnovateLab",
    cliente: "Carlos Ruiz",
    clienteId: "C-002",
    tipo: "compra",
    estado: "Negociación",
    valor: "€1.8M",
    fecha: "2024-01-20",
    descripcion: "Adquisición de laboratorio de innovación",
    sector: "I+D",
    ubicacion: "Barcelona",
    responsable: "Ana Martínez",
    documentosCount: 8,
    actividadesCount: 5,
    targetsCount: 2,
    tareasAbiertas: 1,
    ultimaActualizacion: "2024-02-03",
  },
  {
    id: "M-003",
    empresa: "DataStream Inc",
    cliente: "Ana Martínez",
    clienteId: "C-003",
    tipo: "venta",
    estado: "Due Diligence",
    valor: "€3.2M",
    fecha: "2024-01-10",
    descripcion: "Venta de empresa de análisis de datos",
    sector: "Big Data",
    ubicacion: "Valencia",
    responsable: "Pedro López",
    documentosCount: 15,
    actividadesCount: 12,
    targetsCount: 5,
    tareasAbiertas: 3,
    ultimaActualizacion: "2024-02-04",
  },
  {
    id: "M-004",
    empresa: "GreenEnergy SA",
    cliente: "Laura Sánchez",
    clienteId: "C-004",
    tipo: "venta",
    estado: "Cerrado",
    valor: "€4.1M",
    fecha: "2023-11-05",
    descripcion: "Venta exitosa de empresa de energía renovable",
    sector: "Energía",
    ubicacion: "Sevilla",
    responsable: "Juan Díaz",
    documentosCount: 24,
    actividadesCount: 18,
    targetsCount: 4,
    tareasAbiertas: 0,
    ultimaActualizacion: "2024-01-15",
  },
  {
    id: "M-005",
    empresa: "HealthTech Pro",
    cliente: "Miguel Torres",
    clienteId: "C-005",
    tipo: "venta",
    estado: "Cancelado",
    valor: "€1.2M",
    fecha: "2023-12-10",
    descripcion: "Mandato cancelado por decisión del cliente",
    sector: "Salud",
    ubicacion: "Bilbao",
    responsable: "Ana Martínez",
    documentosCount: 3,
    actividadesCount: 4,
    targetsCount: 1,
    tareasAbiertas: 0,
    ultimaActualizacion: "2023-12-15",
  },
];

// ============================================
// CLIENTES
// ============================================
export const mockClientes: Cliente[] = [
  {
    id: "C-001",
    nombre: "María García",
    empresa: "TechCorp Solutions",
    email: "maria@techcorp.com",
    telefono: "+34 600 123 456",
    mandatos: 2,
    estado: "Activo",
    cargo: "CEO",
    fechaRegistro: "2023-06-15",
    notas: "Cliente VIP, muy interesado en expansión internacional",
  },
  {
    id: "C-002",
    nombre: "Carlos Ruiz",
    empresa: "InnovateLab",
    email: "carlos@innovatelab.com",
    telefono: "+34 600 234 567",
    mandatos: 1,
    estado: "Activo",
    cargo: "Director General",
    fechaRegistro: "2023-08-22",
    notas: "Busca venta rápida, flexible en valoración",
  },
  {
    id: "C-003",
    nombre: "Ana Martínez",
    empresa: "DataStream Inc",
    email: "ana@datastream.com",
    telefono: "+34 600 345 678",
    mandatos: 3,
    estado: "Activo",
    cargo: "Fundadora",
    fechaRegistro: "2023-04-10",
    notas: "Prefiere comprador estratégico, no financiero",
  },
  {
    id: "C-004",
    nombre: "Laura Sánchez",
    empresa: "GreenEnergy SA",
    email: "laura@greenenergy.com",
    telefono: "+34 600 456 789",
    mandatos: 1,
    estado: "Activo",
    cargo: "CFO",
    fechaRegistro: "2023-03-18",
    notas: "Excelente experiencia en proceso de venta",
  },
  {
    id: "C-005",
    nombre: "Miguel Torres",
    empresa: "HealthTech Pro",
    email: "miguel@healthtech.com",
    telefono: "+34 600 567 890",
    mandatos: 1,
    estado: "Inactivo",
    cargo: "CEO",
    fechaRegistro: "2023-09-05",
    notas: "Canceló proceso, posible reactivación en Q3",
  },
];

// ============================================
// EMPRESAS TARGET
// ============================================
export const mockTargets: EmpresaTarget[] = [
  {
    id: "T-001",
    nombre: "FutureTech SA",
    sector: "Tecnología",
    facturacion: "€5.2M",
    empleados: 45,
    ubicacion: "Madrid",
    interes: "Alto",
    estado: "interesada",
    mandatoId: "M-001",
    mandatoNombre: "TechCorp Solutions",
    ultimaActividad: "2024-02-03",
    revenue: 5200000,
    ebitda: 780000,
    descripcion: "Empresa innovadora en soluciones cloud",
    contactoPrincipal: "Roberto Fernández",
    email: "info@futuretech.es",
    telefono: "+34 910 111 222",
    sitioWeb: "https://futuretech.es",
    fechaProspeccion: "2024-01-08",
    interacciones: [
      {
        id: "INT-001",
        tipo: "email",
        titulo: "Primer contacto",
        descripcion: "Email de presentación enviado",
        fecha: "2024-01-08T10:00:00",
        responsable: "Juan Díaz",
      },
      {
        id: "INT-002",
        tipo: "llamada",
        titulo: "Llamada de seguimiento",
        descripcion: "Conversación sobre potencial adquisición",
        fecha: "2024-01-15T14:30:00",
        responsable: "Juan Díaz",
      },
      {
        id: "INT-003",
        tipo: "reunion",
        titulo: "Reunión presencial",
        descripcion: "Presentación detallada de propuesta",
        fecha: "2024-02-03T11:00:00",
        responsable: "Juan Díaz",
      },
    ],
    datosFinancieros: {
      revenue: 5200000,
      ebitda: 780000,
      margenEbitda: 15,
      deuda: 450000,
      capitalCirculante: 320000,
      notas: "Crecimiento sostenido del 20% anual",
    },
  },
  {
    id: "T-002",
    nombre: "BioHealth Labs",
    sector: "Salud",
    facturacion: "€3.8M",
    empleados: 32,
    ubicacion: "Barcelona",
    interes: "Medio",
    estado: "contactada",
    mandatoId: "M-003",
    mandatoNombre: "DataStream Inc",
    ultimaActividad: "2024-01-28",
    revenue: 3800000,
    ebitda: 570000,
    descripcion: "Laboratorio especializado en diagnóstico molecular",
    contactoPrincipal: "Carmen Jiménez",
    email: "contacto@biohealth.es",
    telefono: "+34 930 222 333",
    sitioWeb: "https://biohealth.es",
    fechaProspeccion: "2024-01-12",
    interacciones: [
      {
        id: "INT-004",
        tipo: "email",
        titulo: "Contacto inicial",
        descripcion: "Email de introducción",
        fecha: "2024-01-12T09:00:00",
        responsable: "Ana Martínez",
      },
      {
        id: "INT-005",
        tipo: "llamada",
        titulo: "Primera llamada",
        descripcion: "Discusión sobre interés mutuo",
        fecha: "2024-01-28T16:00:00",
        responsable: "Ana Martínez",
      },
    ],
    datosFinancieros: {
      revenue: 3800000,
      ebitda: 570000,
      margenEbitda: 15,
      deuda: 200000,
      capitalCirculante: 180000,
    },
  },
  {
    id: "T-003",
    nombre: "EcoEnergy Solutions",
    sector: "Energía",
    facturacion: "€7.1M",
    empleados: 68,
    ubicacion: "Valencia",
    interes: "Alto",
    estado: "oferta",
    mandatoId: "M-002",
    mandatoNombre: "InnovateLab",
    ultimaActividad: "2024-02-05",
    revenue: 7100000,
    ebitda: 1420000,
    descripcion: "Soluciones de energía solar y eólica",
    contactoPrincipal: "David Morales",
    email: "david@ecoenergy.es",
    telefono: "+34 960 333 444",
    sitioWeb: "https://ecoenergy.es",
    fechaProspeccion: "2024-01-05",
    interacciones: [
      {
        id: "INT-006",
        tipo: "reunion",
        titulo: "Presentación de oferta",
        descripcion: "Oferta formal presentada",
        fecha: "2024-02-05T10:00:00",
        responsable: "Pedro López",
      },
    ],
    datosFinancieros: {
      revenue: 7100000,
      ebitda: 1420000,
      margenEbitda: 20,
      deuda: 800000,
      capitalCirculante: 650000,
      notas: "Contratos a largo plazo con gobierno",
    },
  },
  {
    id: "T-004",
    nombre: "SmartLogistics Pro",
    sector: "Logística",
    facturacion: "€4.5M",
    empleados: 52,
    ubicacion: "Zaragoza",
    interes: "Bajo",
    estado: "pendiente",
    ultimaActividad: "2024-01-18",
    descripcion: "Plataforma de gestión logística automatizada",
    contactoPrincipal: "Elena Ruiz",
    email: "info@smartlogistics.es",
    telefono: "+34 976 444 555",
    sitioWeb: "https://smartlogistics.es",
    fechaProspeccion: "2024-01-18",
    interacciones: [
      {
        id: "INT-007",
        tipo: "nota",
        titulo: "Prospección inicial",
        descripcion: "Identificado como potencial target",
        fecha: "2024-01-18T12:00:00",
        responsable: "Juan Díaz",
      },
    ],
  },
];

// ============================================
// TAREAS
// ============================================
export const mockTareas: Tarea[] = [
  {
    id: "TAR-001",
    titulo: "Preparar presentación para inversores",
    descripcion: "Crear deck con financials y proyecciones 2024-2026",
    estado: "en-progreso",
    prioridad: "alta",
    fechaVencimiento: "2024-02-15",
    asignado: "Juan Díaz",
    mandatoId: "M-001",
    mandatoNombre: "TechCorp Solutions",
    etiquetas: ["presentación", "financiero"],
  },
  {
    id: "TAR-002",
    titulo: "Revisar contratos de Due Diligence",
    descripcion: "Analizar cláusulas de confidencialidad",
    estado: "pendiente",
    prioridad: "alta",
    fechaVencimiento: "2024-02-10",
    asignado: "Ana Martínez",
    mandatoId: "M-003",
    mandatoNombre: "DataStream Inc",
    etiquetas: ["legal", "urgente"],
  },
  {
    id: "TAR-003",
    titulo: "Llamada de seguimiento con cliente",
    descripcion: "Actualizar sobre progreso de negociación",
    estado: "completada",
    prioridad: "media",
    fechaVencimiento: "2024-02-05",
    asignado: "Pedro López",
    mandatoId: "M-002",
    mandatoNombre: "InnovateLab",
    etiquetas: ["seguimiento"],
  },
  {
    id: "TAR-004",
    titulo: "Contactar con BioHealth Labs",
    descripcion: "Primera llamada de prospección",
    estado: "pendiente",
    prioridad: "media",
    fechaVencimiento: "2024-02-20",
    asignado: "Juan Díaz",
    etiquetas: ["prospección", "target"],
  },
  {
    id: "TAR-005",
    titulo: "Actualizar valoración de mercado",
    descripcion: "Incluir nuevos comparables del sector tech",
    estado: "en-progreso",
    prioridad: "baja",
    fechaVencimiento: "2024-02-25",
    asignado: "Ana Martínez",
    mandatoId: "M-001",
    mandatoNombre: "TechCorp Solutions",
    etiquetas: ["valoración", "análisis"],
  },
];

// ============================================
// DOCUMENTOS
// ============================================
export const mockDocumentos: Documento[] = [
  {
    id: "DOC-001",
    file_name: "NDA_TechCorp_2024.pdf",
    tipo: "NDA",
    mandato_id: "M-001",
    file_size_bytes: 251904,
    mime_type: "application/pdf",
    storage_path: "mock/path/DOC-001.pdf",
    uploaded_by: "Juan Díaz",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "DOC-002",
    file_name: "Due_Diligence_Report_Q4.xlsx",
    tipo: "Due Diligence",
    mandato_id: "M-003",
    file_size_bytes: 1258291,
    mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    storage_path: "mock/path/DOC-002.xlsx",
    uploaded_by: "Ana Martínez",
    created_at: "2024-01-22T10:00:00Z",
    updated_at: "2024-01-22T10:00:00Z",
  },
  {
    id: "DOC-003",
    file_name: "Contrato_Servicios_InnovateLab.docx",
    tipo: "Contrato",
    mandato_id: "M-002",
    file_size_bytes: 191488,
    mime_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    storage_path: "mock/path/DOC-003.docx",
    uploaded_by: "Pedro López",
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-01-20T10:00:00Z",
  },
  {
    id: "DOC-004",
    file_name: "Estados_Financieros_2023.pdf",
    tipo: "Financiero",
    mandato_id: "M-001",
    file_size_bytes: 3565158,
    mime_type: "application/pdf",
    storage_path: "mock/path/DOC-004.pdf",
    uploaded_by: "María García",
    created_at: "2024-01-18T10:00:00Z",
    updated_at: "2024-01-18T10:00:00Z",
  },
  {
    id: "DOC-005",
    file_name: "Informe_Legal_Compliance.pdf",
    tipo: "Legal",
    mandato_id: "M-003",
    file_size_bytes: 912179,
    mime_type: "application/pdf",
    storage_path: "mock/path/DOC-005.pdf",
    uploaded_by: "Ana Martínez",
    created_at: "2024-01-25T10:00:00Z",
    updated_at: "2024-01-25T10:00:00Z",
  },
];

// ============================================
// ACTIVIDADES
// ============================================
export const mockActividades: Actividad[] = [
  {
    id: "ACT-001",
    tipo: "creacion",
    titulo: "Mandato creado",
    descripcion: "Se creó el mandato para TechCorp Solutions",
    usuario: "Juan Díaz",
    fecha: "2024-01-15T10:30:00",
    mandatoId: "M-001",
  },
  {
    id: "ACT-002",
    tipo: "documento",
    titulo: "Documento subido",
    descripcion: "NDA firmado y subido al sistema",
    usuario: "Juan Díaz",
    fecha: "2024-01-15T14:20:00",
    mandatoId: "M-001",
  },
  {
    id: "ACT-003",
    tipo: "estado",
    titulo: "Estado actualizado",
    descripcion: "Cambio de estado a 'En progreso'",
    usuario: "Juan Díaz",
    fecha: "2024-01-16T09:15:00",
    mandatoId: "M-001",
  },
  {
    id: "ACT-004",
    tipo: "comentario",
    titulo: "Comentario añadido",
    descripcion: "Cliente confirma interés de 3 potenciales compradores",
    usuario: "Ana Martínez",
    fecha: "2024-01-18T11:45:00",
    mandatoId: "M-001",
  },
  {
    id: "ACT-005",
    tipo: "actualizacion",
    titulo: "Valoración actualizada",
    descripcion: "Nueva valoración de €2.5M basada en comparables",
    usuario: "Pedro López",
    fecha: "2024-01-20T16:30:00",
    mandatoId: "M-001",
  },
];
